# coding: utf-8

"""
    Yanado REST API

    REST API for Yanado

    OpenAPI spec version: 1.0
    Contact: prle@yanado.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UpdateRequestTask(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'archived': 'bool',
        'assignee_id': 'str',
        'description': 'str',
        'due_date': 'datetime',
        'form': 'dict(str, str)',
        'list_id': 'str',
        'name': 'str',
        'status_id': 'str'
    }

    attribute_map = {
        'archived': 'archived',
        'assignee_id': 'assigneeId',
        'description': 'description',
        'due_date': 'dueDate',
        'form': 'form',
        'list_id': 'listId',
        'name': 'name',
        'status_id': 'statusId'
    }

    def __init__(self, archived=None, assignee_id=None, description=None, due_date=None, form=None, list_id=None, name=None, status_id=None):
        """
        UpdateRequestTask - a model defined in Swagger
        """

        self._archived = None
        self._assignee_id = None
        self._description = None
        self._due_date = None
        self._form = None
        self._list_id = None
        self._name = None
        self._status_id = None

        if archived is not None:
          self.archived = archived
        if assignee_id is not None:
          self.assignee_id = assignee_id
        if description is not None:
          self.description = description
        if due_date is not None:
          self.due_date = due_date
        if form is not None:
          self.form = form
        if list_id is not None:
          self.list_id = list_id
        if name is not None:
          self.name = name
        if status_id is not None:
          self.status_id = status_id

    @property
    def archived(self):
        """
        Gets the archived of this UpdateRequestTask.
        Archived

        :return: The archived of this UpdateRequestTask.
        :rtype: bool
        """
        return self._archived

    @archived.setter
    def archived(self, archived):
        """
        Sets the archived of this UpdateRequestTask.
        Archived

        :param archived: The archived of this UpdateRequestTask.
        :type: bool
        """

        self._archived = archived

    @property
    def assignee_id(self):
        """
        Gets the assignee_id of this UpdateRequestTask.
        Assignee id

        :return: The assignee_id of this UpdateRequestTask.
        :rtype: str
        """
        return self._assignee_id

    @assignee_id.setter
    def assignee_id(self, assignee_id):
        """
        Sets the assignee_id of this UpdateRequestTask.
        Assignee id

        :param assignee_id: The assignee_id of this UpdateRequestTask.
        :type: str
        """

        self._assignee_id = assignee_id

    @property
    def description(self):
        """
        Gets the description of this UpdateRequestTask.
        Description

        :return: The description of this UpdateRequestTask.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this UpdateRequestTask.
        Description

        :param description: The description of this UpdateRequestTask.
        :type: str
        """

        self._description = description

    @property
    def due_date(self):
        """
        Gets the due_date of this UpdateRequestTask.
        Due date

        :return: The due_date of this UpdateRequestTask.
        :rtype: datetime
        """
        return self._due_date

    @due_date.setter
    def due_date(self, due_date):
        """
        Sets the due_date of this UpdateRequestTask.
        Due date

        :param due_date: The due_date of this UpdateRequestTask.
        :type: datetime
        """

        self._due_date = due_date

    @property
    def form(self):
        """
        Gets the form of this UpdateRequestTask.

        :return: The form of this UpdateRequestTask.
        :rtype: dict(str, str)
        """
        return self._form

    @form.setter
    def form(self, form):
        """
        Sets the form of this UpdateRequestTask.

        :param form: The form of this UpdateRequestTask.
        :type: dict(str, str)
        """

        self._form = form

    @property
    def list_id(self):
        """
        Gets the list_id of this UpdateRequestTask.
        List id

        :return: The list_id of this UpdateRequestTask.
        :rtype: str
        """
        return self._list_id

    @list_id.setter
    def list_id(self, list_id):
        """
        Sets the list_id of this UpdateRequestTask.
        List id

        :param list_id: The list_id of this UpdateRequestTask.
        :type: str
        """

        self._list_id = list_id

    @property
    def name(self):
        """
        Gets the name of this UpdateRequestTask.
        Name

        :return: The name of this UpdateRequestTask.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this UpdateRequestTask.
        Name

        :param name: The name of this UpdateRequestTask.
        :type: str
        """

        self._name = name

    @property
    def status_id(self):
        """
        Gets the status_id of this UpdateRequestTask.
        Status Id

        :return: The status_id of this UpdateRequestTask.
        :rtype: str
        """
        return self._status_id

    @status_id.setter
    def status_id(self, status_id):
        """
        Sets the status_id of this UpdateRequestTask.
        Status Id

        :param status_id: The status_id of this UpdateRequestTask.
        :type: str
        """

        self._status_id = status_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UpdateRequestTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
