=begin
#Yanado REST API

#REST API for Yanado

OpenAPI spec version: 1.0
Contact: prle@yanado.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'com_yanado_public_api/api_client'
require 'com_yanado_public_api/api_error'
require 'com_yanado_public_api/version'
require 'com_yanado_public_api/configuration'

# Models
require 'com_yanado_public_api/models/comment'
require 'com_yanado_public_api/models/email_task'
require 'com_yanado_public_api/models/list'
require 'com_yanado_public_api/models/notification'
require 'com_yanado_public_api/models/request_task'
require 'com_yanado_public_api/models/status'
require 'com_yanado_public_api/models/task'
require 'com_yanado_public_api/models/update_request_task'
require 'com_yanado_public_api/models/user'

# APIs
require 'com_yanado_public_api/api/comments_api'
require 'com_yanado_public_api/api/emailtasks_api'
require 'com_yanado_public_api/api/lists_api'
require 'com_yanado_public_api/api/notifications_api'
require 'com_yanado_public_api/api/statuses_api'
require 'com_yanado_public_api/api/tasks_api'
require 'com_yanado_public_api/api/users_api'

module ComYanadoPublicApi
  class << self
    # Customize default settings for the SDK using block.
    #   ComYanadoPublicApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
