/*
 * Yanado REST API
 * REST API for Yanado
 *
 * OpenAPI spec version: 1.0
 * Contact: prle@yanado.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yanado.api;

import com.yanado.invoker.ApiException;
import com.yanado.model.EmailTask;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmailTasksApi
 */
@Ignore
public class EmailTasksApiTest {

    private final EmailTasksApi api = new EmailTasksApi();

    
    /**
     * Get tasks with emails attached
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEmailTasksTest() throws ApiException {
        String listId = null;
        String assignee = null;
        String statusId = null;
        String query = null;
        List<EmailTask> response = api.getEmailTasks(listId, assignee, statusId, query);

        // TODO: test validations
    }
    
}
