/*
 * Yanado REST API
 * REST API for Yanado
 *
 * OpenAPI spec version: 1.0
 * Contact: prle@yanado.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yanado.api;

import com.yanado.invoker.ApiException;
import com.yanado.model.RequestTask;
import com.yanado.model.Task;
import com.yanado.model.UpdateRequestTask;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TasksApi
 */
@Ignore
public class TasksApiTest {

    private final TasksApi api = new TasksApi();

    
    /**
     * Create task
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTaskTest() throws ApiException {
        RequestTask taskRequest = null;
        Task response = api.createTask(taskRequest);

        // TODO: test validations
    }
    
    /**
     * Get task
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTaskTest() throws ApiException {
        String taskId = null;
        Task response = api.getTask(taskId);

        // TODO: test validations
    }
    
    /**
     * Get tasks
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTasksTest() throws ApiException {
        String listId = null;
        String assignee = null;
        String statusId = null;
        String query = null;
        List<Task> response = api.getTasks(listId, assignee, statusId, query);

        // TODO: test validations
    }
    
    /**
     * Update task
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTaskTest() throws ApiException {
        String taskId = null;
        UpdateRequestTask taskRequest = null;
        Task response = api.updateTask(taskId, taskRequest);

        // TODO: test validations
    }
    
}
