<?php
/**
 * EmailTaskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com.yanado.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yanado REST API
 *
 * REST API for Yanado
 *
 * OpenAPI spec version: 1.0
 * Contact: prle@yanado.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com.yanado.invoker;

/**
 * EmailTaskTest Class Doc Comment
 *
 * @category    Class */
// * @description EmailTask
/**
 * @package     com.yanado.invoker
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmailTaskTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmailTask"
     */
    public function testEmailTask()
    {
    }

    /**
     * Test attribute "assignee_id"
     */
    public function testPropertyAssigneeId()
    {
    }

    /**
     * Test attribute "assignee_name"
     */
    public function testPropertyAssigneeName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "list_id"
     */
    public function testPropertyListId()
    {
    }

    /**
     * Test attribute "list_name"
     */
    public function testPropertyListName()
    {
    }

    /**
     * Test attribute "participant_email"
     */
    public function testPropertyParticipantEmail()
    {
    }

    /**
     * Test attribute "participant_name"
     */
    public function testPropertyParticipantName()
    {
    }

    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {
    }

    /**
     * Test attribute "status_name"
     */
    public function testPropertyStatusName()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "task_created"
     */
    public function testPropertyTaskCreated()
    {
    }

    /**
     * Test attribute "task_description"
     */
    public function testPropertyTaskDescription()
    {
    }

    /**
     * Test attribute "task_due_date"
     */
    public function testPropertyTaskDueDate()
    {
    }

    /**
     * Test attribute "task_high_priority"
     */
    public function testPropertyTaskHighPriority()
    {
    }

    /**
     * Test attribute "task_id"
     */
    public function testPropertyTaskId()
    {
    }

    /**
     * Test attribute "task_name"
     */
    public function testPropertyTaskName()
    {
    }

    /**
     * Test attribute "thread_id"
     */
    public function testPropertyThreadId()
    {
    }
}
