<?php
/**
 * RequestTaskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com.yanado.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yanado REST API
 *
 * REST API for Yanado
 *
 * OpenAPI spec version: 1.0
 * Contact: prle@yanado.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com.yanado.invoker;

/**
 * RequestTaskTest Class Doc Comment
 *
 * @category    Class */
// * @description RequestTask
/**
 * @package     com.yanado.invoker
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestTaskTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RequestTask"
     */
    public function testRequestTask()
    {
    }

    /**
     * Test attribute "assignee_id"
     */
    public function testPropertyAssigneeId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "form"
     */
    public function testPropertyForm()
    {
    }

    /**
     * Test attribute "list_id"
     */
    public function testPropertyListId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {
    }

    /**
     * Test attribute "thread_email"
     */
    public function testPropertyThreadEmail()
    {
    }

    /**
     * Test attribute "thread_id"
     */
    public function testPropertyThreadId()
    {
    }

    /**
     * Test attribute "thread_name"
     */
    public function testPropertyThreadName()
    {
    }

    /**
     * Test attribute "thread_subject"
     */
    public function testPropertyThreadSubject()
    {
    }
}
