<?php
/**
 * RequestTask
 *
 * PHP version 5
 *
 * @category Class
 * @package  com.yanado.invoker
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yanado REST API
 *
 * REST API for Yanado
 *
 * OpenAPI spec version: 1.0
 * Contact: prle@yanado.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace com.yanado.invoker\com.yanado.model;

use \ArrayAccess;

/**
 * RequestTask Class Doc Comment
 *
 * @category    Class
 * @package     com.yanado.invoker
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestTask implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Request Task';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'assignee_id' => 'string',
        'description' => 'string',
        'due_date' => '\DateTime',
        'form' => 'map[string,string]',
        'list_id' => 'string',
        'name' => 'string',
        'status_id' => 'string',
        'thread_email' => 'string',
        'thread_id' => 'string',
        'thread_name' => 'string',
        'thread_subject' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'assignee_id' => null,
        'description' => null,
        'due_date' => 'date-time',
        'form' => null,
        'list_id' => null,
        'name' => null,
        'status_id' => null,
        'thread_email' => null,
        'thread_id' => null,
        'thread_name' => null,
        'thread_subject' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'assignee_id' => 'assigneeId',
        'description' => 'description',
        'due_date' => 'dueDate',
        'form' => 'form',
        'list_id' => 'listId',
        'name' => 'name',
        'status_id' => 'statusId',
        'thread_email' => 'threadEmail',
        'thread_id' => 'threadId',
        'thread_name' => 'threadName',
        'thread_subject' => 'threadSubject'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'assignee_id' => 'setAssigneeId',
        'description' => 'setDescription',
        'due_date' => 'setDueDate',
        'form' => 'setForm',
        'list_id' => 'setListId',
        'name' => 'setName',
        'status_id' => 'setStatusId',
        'thread_email' => 'setThreadEmail',
        'thread_id' => 'setThreadId',
        'thread_name' => 'setThreadName',
        'thread_subject' => 'setThreadSubject'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'assignee_id' => 'getAssigneeId',
        'description' => 'getDescription',
        'due_date' => 'getDueDate',
        'form' => 'getForm',
        'list_id' => 'getListId',
        'name' => 'getName',
        'status_id' => 'getStatusId',
        'thread_email' => 'getThreadEmail',
        'thread_id' => 'getThreadId',
        'thread_name' => 'getThreadName',
        'thread_subject' => 'getThreadSubject'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['assignee_id'] = isset($data['assignee_id']) ? $data['assignee_id'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['due_date'] = isset($data['due_date']) ? $data['due_date'] : null;
        $this->container['form'] = isset($data['form']) ? $data['form'] : null;
        $this->container['list_id'] = isset($data['list_id']) ? $data['list_id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['status_id'] = isset($data['status_id']) ? $data['status_id'] : null;
        $this->container['thread_email'] = isset($data['thread_email']) ? $data['thread_email'] : null;
        $this->container['thread_id'] = isset($data['thread_id']) ? $data['thread_id'] : null;
        $this->container['thread_name'] = isset($data['thread_name']) ? $data['thread_name'] : null;
        $this->container['thread_subject'] = isset($data['thread_subject']) ? $data['thread_subject'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['list_id'] === null) {
            $invalid_properties[] = "'list_id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalid_properties[] = "'name' can't be null";
        }
        if ($this->container['status_id'] === null) {
            $invalid_properties[] = "'status_id' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['list_id'] === null) {
            return false;
        }
        if ($this->container['name'] === null) {
            return false;
        }
        if ($this->container['status_id'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets assignee_id
     * @return string
     */
    public function getAssigneeId()
    {
        return $this->container['assignee_id'];
    }

    /**
     * Sets assignee_id
     * @param string $assignee_id Assignee id
     * @return $this
     */
    public function setAssigneeId($assignee_id)
    {
        $this->container['assignee_id'] = $assignee_id;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description Description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets due_date
     * @return \DateTime
     */
    public function getDueDate()
    {
        return $this->container['due_date'];
    }

    /**
     * Sets due_date
     * @param \DateTime $due_date Due date
     * @return $this
     */
    public function setDueDate($due_date)
    {
        $this->container['due_date'] = $due_date;

        return $this;
    }

    /**
     * Gets form
     * @return map[string,string]
     */
    public function getForm()
    {
        return $this->container['form'];
    }

    /**
     * Sets form
     * @param map[string,string] $form
     * @return $this
     */
    public function setForm($form)
    {
        $this->container['form'] = $form;

        return $this;
    }

    /**
     * Gets list_id
     * @return string
     */
    public function getListId()
    {
        return $this->container['list_id'];
    }

    /**
     * Sets list_id
     * @param string $list_id List id
     * @return $this
     */
    public function setListId($list_id)
    {
        $this->container['list_id'] = $list_id;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name Name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets status_id
     * @return string
     */
    public function getStatusId()
    {
        return $this->container['status_id'];
    }

    /**
     * Sets status_id
     * @param string $status_id Status Id
     * @return $this
     */
    public function setStatusId($status_id)
    {
        $this->container['status_id'] = $status_id;

        return $this;
    }

    /**
     * Gets thread_email
     * @return string
     */
    public function getThreadEmail()
    {
        return $this->container['thread_email'];
    }

    /**
     * Sets thread_email
     * @param string $thread_email Participant email
     * @return $this
     */
    public function setThreadEmail($thread_email)
    {
        $this->container['thread_email'] = $thread_email;

        return $this;
    }

    /**
     * Gets thread_id
     * @return string
     */
    public function getThreadId()
    {
        return $this->container['thread_id'];
    }

    /**
     * Sets thread_id
     * @param string $thread_id Thread id
     * @return $this
     */
    public function setThreadId($thread_id)
    {
        $this->container['thread_id'] = $thread_id;

        return $this;
    }

    /**
     * Gets thread_name
     * @return string
     */
    public function getThreadName()
    {
        return $this->container['thread_name'];
    }

    /**
     * Sets thread_name
     * @param string $thread_name Subject
     * @return $this
     */
    public function setThreadName($thread_name)
    {
        $this->container['thread_name'] = $thread_name;

        return $this;
    }

    /**
     * Gets thread_subject
     * @return string
     */
    public function getThreadSubject()
    {
        return $this->container['thread_subject'];
    }

    /**
     * Sets thread_subject
     * @param string $thread_subject Subject
     * @return $this
     */
    public function setThreadSubject($thread_subject)
    {
        $this->container['thread_subject'] = $thread_subject;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\com.yanado.invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\com.yanado.invoker\ObjectSerializer::sanitizeForSerialization($this));
    }
}


