<?php
/**
 * Task
 *
 * PHP version 5
 *
 * @category Class
 * @package  com.yanado.invoker
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yanado REST API
 *
 * REST API for Yanado
 *
 * OpenAPI spec version: 1.0
 * Contact: prle@yanado.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace com.yanado.invoker\com.yanado.model;

use \ArrayAccess;

/**
 * Task Class Doc Comment
 *
 * @category    Class
 * @package     com.yanado.invoker
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Task implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Task';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'assignee_id' => 'string',
        'assignee_name' => 'string',
        'create_time' => '\DateTime',
        'description' => 'string',
        'due_date' => '\DateTime',
        'high_priority' => 'bool',
        'list_id' => 'string',
        'list_name' => 'string',
        'name' => 'string',
        'status_id' => 'string',
        'status_name' => 'string',
        'task_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'assignee_id' => null,
        'assignee_name' => null,
        'create_time' => 'date-time',
        'description' => null,
        'due_date' => 'date-time',
        'high_priority' => null,
        'list_id' => null,
        'list_name' => null,
        'name' => null,
        'status_id' => null,
        'status_name' => null,
        'task_id' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'assignee_id' => 'assigneeId',
        'assignee_name' => 'assigneeName',
        'create_time' => 'createTime',
        'description' => 'description',
        'due_date' => 'dueDate',
        'high_priority' => 'highPriority',
        'list_id' => 'listId',
        'list_name' => 'listName',
        'name' => 'name',
        'status_id' => 'statusId',
        'status_name' => 'statusName',
        'task_id' => 'taskId'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'assignee_id' => 'setAssigneeId',
        'assignee_name' => 'setAssigneeName',
        'create_time' => 'setCreateTime',
        'description' => 'setDescription',
        'due_date' => 'setDueDate',
        'high_priority' => 'setHighPriority',
        'list_id' => 'setListId',
        'list_name' => 'setListName',
        'name' => 'setName',
        'status_id' => 'setStatusId',
        'status_name' => 'setStatusName',
        'task_id' => 'setTaskId'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'assignee_id' => 'getAssigneeId',
        'assignee_name' => 'getAssigneeName',
        'create_time' => 'getCreateTime',
        'description' => 'getDescription',
        'due_date' => 'getDueDate',
        'high_priority' => 'getHighPriority',
        'list_id' => 'getListId',
        'list_name' => 'getListName',
        'name' => 'getName',
        'status_id' => 'getStatusId',
        'status_name' => 'getStatusName',
        'task_id' => 'getTaskId'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['assignee_id'] = isset($data['assignee_id']) ? $data['assignee_id'] : null;
        $this->container['assignee_name'] = isset($data['assignee_name']) ? $data['assignee_name'] : null;
        $this->container['create_time'] = isset($data['create_time']) ? $data['create_time'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['due_date'] = isset($data['due_date']) ? $data['due_date'] : null;
        $this->container['high_priority'] = isset($data['high_priority']) ? $data['high_priority'] : null;
        $this->container['list_id'] = isset($data['list_id']) ? $data['list_id'] : null;
        $this->container['list_name'] = isset($data['list_name']) ? $data['list_name'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['status_id'] = isset($data['status_id']) ? $data['status_id'] : null;
        $this->container['status_name'] = isset($data['status_name']) ? $data['status_name'] : null;
        $this->container['task_id'] = isset($data['task_id']) ? $data['task_id'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets assignee_id
     * @return string
     */
    public function getAssigneeId()
    {
        return $this->container['assignee_id'];
    }

    /**
     * Sets assignee_id
     * @param string $assignee_id Assignee id
     * @return $this
     */
    public function setAssigneeId($assignee_id)
    {
        $this->container['assignee_id'] = $assignee_id;

        return $this;
    }

    /**
     * Gets assignee_name
     * @return string
     */
    public function getAssigneeName()
    {
        return $this->container['assignee_name'];
    }

    /**
     * Sets assignee_name
     * @param string $assignee_name Assignee name
     * @return $this
     */
    public function setAssigneeName($assignee_name)
    {
        $this->container['assignee_name'] = $assignee_name;

        return $this;
    }

    /**
     * Gets create_time
     * @return \DateTime
     */
    public function getCreateTime()
    {
        return $this->container['create_time'];
    }

    /**
     * Sets create_time
     * @param \DateTime $create_time Created
     * @return $this
     */
    public function setCreateTime($create_time)
    {
        $this->container['create_time'] = $create_time;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description Description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets due_date
     * @return \DateTime
     */
    public function getDueDate()
    {
        return $this->container['due_date'];
    }

    /**
     * Sets due_date
     * @param \DateTime $due_date Due date
     * @return $this
     */
    public function setDueDate($due_date)
    {
        $this->container['due_date'] = $due_date;

        return $this;
    }

    /**
     * Gets high_priority
     * @return bool
     */
    public function getHighPriority()
    {
        return $this->container['high_priority'];
    }

    /**
     * Sets high_priority
     * @param bool $high_priority Hight priority
     * @return $this
     */
    public function setHighPriority($high_priority)
    {
        $this->container['high_priority'] = $high_priority;

        return $this;
    }

    /**
     * Gets list_id
     * @return string
     */
    public function getListId()
    {
        return $this->container['list_id'];
    }

    /**
     * Sets list_id
     * @param string $list_id List id
     * @return $this
     */
    public function setListId($list_id)
    {
        $this->container['list_id'] = $list_id;

        return $this;
    }

    /**
     * Gets list_name
     * @return string
     */
    public function getListName()
    {
        return $this->container['list_name'];
    }

    /**
     * Sets list_name
     * @param string $list_name List name
     * @return $this
     */
    public function setListName($list_name)
    {
        $this->container['list_name'] = $list_name;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name Name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets status_id
     * @return string
     */
    public function getStatusId()
    {
        return $this->container['status_id'];
    }

    /**
     * Sets status_id
     * @param string $status_id Status Id
     * @return $this
     */
    public function setStatusId($status_id)
    {
        $this->container['status_id'] = $status_id;

        return $this;
    }

    /**
     * Gets status_name
     * @return string
     */
    public function getStatusName()
    {
        return $this->container['status_name'];
    }

    /**
     * Sets status_name
     * @param string $status_name Status name
     * @return $this
     */
    public function setStatusName($status_name)
    {
        $this->container['status_name'] = $status_name;

        return $this;
    }

    /**
     * Gets task_id
     * @return string
     */
    public function getTaskId()
    {
        return $this->container['task_id'];
    }

    /**
     * Sets task_id
     * @param string $task_id Id
     * @return $this
     */
    public function setTaskId($task_id)
    {
        $this->container['task_id'] = $task_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\com.yanado.invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\com.yanado.invoker\ObjectSerializer::sanitizeForSerialization($this));
    }
}


