=begin
#Yanado REST API

#REST API for Yanado

OpenAPI spec version: 1.0
Contact: prle@yanado.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for ComYanadoPublicApi::NotificationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NotificationsApi' do
  before do
    # run before each test
    @instance = ComYanadoPublicApi::NotificationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NotificationsApi' do
    it 'should create an instance of NotificationsApi' do
      expect(@instance).to be_instance_of(ComYanadoPublicApi::NotificationsApi)
    end
  end

  # unit tests for get_notifications
  # Get notifications
  # 
  # @param type Notification type
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :any_user Any user
  # @option opts [String] :list_id List id
  # @return [Array<Notification>]
  describe 'get_notifications test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
