<?php
/**
 * TasksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  com.yanado.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yanado REST API
 *
 * REST API for Yanado
 *
 * OpenAPI spec version: 1.0
 * Contact: prle@yanado.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace com.yanado.invoker;

use \com.yanado.invoker\Configuration;
use \com.yanado.invoker\ApiClient;
use \com.yanado.invoker\ApiException;
use \com.yanado.invoker\ObjectSerializer;

/**
 * TasksApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.yanado.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TasksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createTask
     *
     * Create task.
     *
     */
    public function testCreateTask()
    {
    }

    /**
     * Test case for getTask
     *
     * Get task.
     *
     */
    public function testGetTask()
    {
    }

    /**
     * Test case for getTasks
     *
     * Get tasks.
     *
     */
    public function testGetTasks()
    {
    }

    /**
     * Test case for updateTask
     *
     * Update task.
     *
     */
    public function testUpdateTask()
    {
    }
}
