<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  com.yanado.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yanado REST API
 *
 * REST API for Yanado
 *
 * OpenAPI spec version: 1.0
 * Contact: prle@yanado.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace com.yanado.invoker;

use \com.yanado.invoker\Configuration;
use \com.yanado.invoker\ApiClient;
use \com.yanado.invoker\ApiException;
use \com.yanado.invoker\ObjectSerializer;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.yanado.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getUsers
     *
     * Get users from a team.
     *
     */
    public function testGetUsers()
    {
    }

    /**
     * Test case for getUsersFromList
     *
     * Get users from a list.
     *
     */
    public function testGetUsersFromList()
    {
    }
}
