/*
 * Yanado REST API
 * REST API for Yanado
 *
 * OpenAPI spec version: 1.0
 * Contact: prle@yanado.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yanado.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * RequestTask
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-21T10:08:54.066Z")
public class RequestTask {
  @SerializedName("assigneeId")
  private String assigneeId = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("dueDate")
  private OffsetDateTime dueDate = null;

  @SerializedName("form")
  private Map<String, String> form = null;

  @SerializedName("listId")
  private String listId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("statusId")
  private String statusId = null;

  @SerializedName("threadEmail")
  private String threadEmail = null;

  @SerializedName("threadId")
  private String threadId = null;

  @SerializedName("threadName")
  private String threadName = null;

  @SerializedName("threadSubject")
  private String threadSubject = null;

  public RequestTask assigneeId(String assigneeId) {
    this.assigneeId = assigneeId;
    return this;
  }

   /**
   * Assignee id
   * @return assigneeId
  **/
  @ApiModelProperty(value = "Assignee id")
  public String getAssigneeId() {
    return assigneeId;
  }

  public void setAssigneeId(String assigneeId) {
    this.assigneeId = assigneeId;
  }

  public RequestTask description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description
   * @return description
  **/
  @ApiModelProperty(value = "Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RequestTask dueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Due date
   * @return dueDate
  **/
  @ApiModelProperty(value = "Due date")
  public OffsetDateTime getDueDate() {
    return dueDate;
  }

  public void setDueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
  }

  public RequestTask form(Map<String, String> form) {
    this.form = form;
    return this;
  }

  public RequestTask putFormItem(String key, String formItem) {
    if (this.form == null) {
      this.form = new HashMap<String, String>();
    }
    this.form.put(key, formItem);
    return this;
  }

   /**
   * Get form
   * @return form
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getForm() {
    return form;
  }

  public void setForm(Map<String, String> form) {
    this.form = form;
  }

  public RequestTask listId(String listId) {
    this.listId = listId;
    return this;
  }

   /**
   * List id
   * @return listId
  **/
  @ApiModelProperty(required = true, value = "List id")
  public String getListId() {
    return listId;
  }

  public void setListId(String listId) {
    this.listId = listId;
  }

  public RequestTask name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RequestTask statusId(String statusId) {
    this.statusId = statusId;
    return this;
  }

   /**
   * Status Id
   * @return statusId
  **/
  @ApiModelProperty(required = true, value = "Status Id")
  public String getStatusId() {
    return statusId;
  }

  public void setStatusId(String statusId) {
    this.statusId = statusId;
  }

  public RequestTask threadEmail(String threadEmail) {
    this.threadEmail = threadEmail;
    return this;
  }

   /**
   * Participant email
   * @return threadEmail
  **/
  @ApiModelProperty(value = "Participant email")
  public String getThreadEmail() {
    return threadEmail;
  }

  public void setThreadEmail(String threadEmail) {
    this.threadEmail = threadEmail;
  }

  public RequestTask threadId(String threadId) {
    this.threadId = threadId;
    return this;
  }

   /**
   * Thread id
   * @return threadId
  **/
  @ApiModelProperty(value = "Thread id")
  public String getThreadId() {
    return threadId;
  }

  public void setThreadId(String threadId) {
    this.threadId = threadId;
  }

  public RequestTask threadName(String threadName) {
    this.threadName = threadName;
    return this;
  }

   /**
   * Subject
   * @return threadName
  **/
  @ApiModelProperty(value = "Subject")
  public String getThreadName() {
    return threadName;
  }

  public void setThreadName(String threadName) {
    this.threadName = threadName;
  }

  public RequestTask threadSubject(String threadSubject) {
    this.threadSubject = threadSubject;
    return this;
  }

   /**
   * Subject
   * @return threadSubject
  **/
  @ApiModelProperty(value = "Subject")
  public String getThreadSubject() {
    return threadSubject;
  }

  public void setThreadSubject(String threadSubject) {
    this.threadSubject = threadSubject;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestTask requestTask = (RequestTask) o;
    return Objects.equals(this.assigneeId, requestTask.assigneeId) &&
        Objects.equals(this.description, requestTask.description) &&
        Objects.equals(this.dueDate, requestTask.dueDate) &&
        Objects.equals(this.form, requestTask.form) &&
        Objects.equals(this.listId, requestTask.listId) &&
        Objects.equals(this.name, requestTask.name) &&
        Objects.equals(this.statusId, requestTask.statusId) &&
        Objects.equals(this.threadEmail, requestTask.threadEmail) &&
        Objects.equals(this.threadId, requestTask.threadId) &&
        Objects.equals(this.threadName, requestTask.threadName) &&
        Objects.equals(this.threadSubject, requestTask.threadSubject);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assigneeId, description, dueDate, form, listId, name, statusId, threadEmail, threadId, threadName, threadSubject);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestTask {\n");
    
    sb.append("    assigneeId: ").append(toIndentedString(assigneeId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    listId: ").append(toIndentedString(listId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    statusId: ").append(toIndentedString(statusId)).append("\n");
    sb.append("    threadEmail: ").append(toIndentedString(threadEmail)).append("\n");
    sb.append("    threadId: ").append(toIndentedString(threadId)).append("\n");
    sb.append("    threadName: ").append(toIndentedString(threadName)).append("\n");
    sb.append("    threadSubject: ").append(toIndentedString(threadSubject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

