/*
 * Yanado REST API
 * REST API for Yanado
 *
 * OpenAPI spec version: 1.0
 * Contact: prle@yanado.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yanado.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * Task
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-21T10:08:54.066Z")
public class Task {
  @SerializedName("assigneeId")
  private String assigneeId = null;

  @SerializedName("assigneeName")
  private String assigneeName = null;

  @SerializedName("createTime")
  private OffsetDateTime createTime = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("dueDate")
  private OffsetDateTime dueDate = null;

  @SerializedName("highPriority")
  private Boolean highPriority = null;

  @SerializedName("listId")
  private String listId = null;

  @SerializedName("listName")
  private String listName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("statusId")
  private String statusId = null;

  @SerializedName("statusName")
  private String statusName = null;

  @SerializedName("taskId")
  private String taskId = null;

  public Task assigneeId(String assigneeId) {
    this.assigneeId = assigneeId;
    return this;
  }

   /**
   * Assignee id
   * @return assigneeId
  **/
  @ApiModelProperty(value = "Assignee id")
  public String getAssigneeId() {
    return assigneeId;
  }

  public void setAssigneeId(String assigneeId) {
    this.assigneeId = assigneeId;
  }

  public Task assigneeName(String assigneeName) {
    this.assigneeName = assigneeName;
    return this;
  }

   /**
   * Assignee name
   * @return assigneeName
  **/
  @ApiModelProperty(value = "Assignee name")
  public String getAssigneeName() {
    return assigneeName;
  }

  public void setAssigneeName(String assigneeName) {
    this.assigneeName = assigneeName;
  }

  public Task createTime(OffsetDateTime createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * Created
   * @return createTime
  **/
  @ApiModelProperty(value = "Created")
  public OffsetDateTime getCreateTime() {
    return createTime;
  }

  public void setCreateTime(OffsetDateTime createTime) {
    this.createTime = createTime;
  }

  public Task description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description
   * @return description
  **/
  @ApiModelProperty(value = "Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Task dueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Due date
   * @return dueDate
  **/
  @ApiModelProperty(value = "Due date")
  public OffsetDateTime getDueDate() {
    return dueDate;
  }

  public void setDueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
  }

  public Task highPriority(Boolean highPriority) {
    this.highPriority = highPriority;
    return this;
  }

   /**
   * Hight priority
   * @return highPriority
  **/
  @ApiModelProperty(example = "false", value = "Hight priority")
  public Boolean getHighPriority() {
    return highPriority;
  }

  public void setHighPriority(Boolean highPriority) {
    this.highPriority = highPriority;
  }

  public Task listId(String listId) {
    this.listId = listId;
    return this;
  }

   /**
   * List id
   * @return listId
  **/
  @ApiModelProperty(value = "List id")
  public String getListId() {
    return listId;
  }

  public void setListId(String listId) {
    this.listId = listId;
  }

  public Task listName(String listName) {
    this.listName = listName;
    return this;
  }

   /**
   * List name
   * @return listName
  **/
  @ApiModelProperty(value = "List name")
  public String getListName() {
    return listName;
  }

  public void setListName(String listName) {
    this.listName = listName;
  }

  public Task name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Task statusId(String statusId) {
    this.statusId = statusId;
    return this;
  }

   /**
   * Status Id
   * @return statusId
  **/
  @ApiModelProperty(value = "Status Id")
  public String getStatusId() {
    return statusId;
  }

  public void setStatusId(String statusId) {
    this.statusId = statusId;
  }

  public Task statusName(String statusName) {
    this.statusName = statusName;
    return this;
  }

   /**
   * Status name
   * @return statusName
  **/
  @ApiModelProperty(value = "Status name")
  public String getStatusName() {
    return statusName;
  }

  public void setStatusName(String statusName) {
    this.statusName = statusName;
  }

  public Task taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Id
   * @return taskId
  **/
  @ApiModelProperty(value = "Id")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Task task = (Task) o;
    return Objects.equals(this.assigneeId, task.assigneeId) &&
        Objects.equals(this.assigneeName, task.assigneeName) &&
        Objects.equals(this.createTime, task.createTime) &&
        Objects.equals(this.description, task.description) &&
        Objects.equals(this.dueDate, task.dueDate) &&
        Objects.equals(this.highPriority, task.highPriority) &&
        Objects.equals(this.listId, task.listId) &&
        Objects.equals(this.listName, task.listName) &&
        Objects.equals(this.name, task.name) &&
        Objects.equals(this.statusId, task.statusId) &&
        Objects.equals(this.statusName, task.statusName) &&
        Objects.equals(this.taskId, task.taskId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assigneeId, assigneeName, createTime, description, dueDate, highPriority, listId, listName, name, statusId, statusName, taskId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Task {\n");
    
    sb.append("    assigneeId: ").append(toIndentedString(assigneeId)).append("\n");
    sb.append("    assigneeName: ").append(toIndentedString(assigneeName)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    highPriority: ").append(toIndentedString(highPriority)).append("\n");
    sb.append("    listId: ").append(toIndentedString(listId)).append("\n");
    sb.append("    listName: ").append(toIndentedString(listName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    statusId: ").append(toIndentedString(statusId)).append("\n");
    sb.append("    statusName: ").append(toIndentedString(statusName)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

