# coding: utf-8

"""
    Yanado REST API

    REST API for Yanado

    OpenAPI spec version: 1.0
    Contact: prle@yanado.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import com_yanado_public_api
from com_yanado_public_api.rest import ApiException
from com_yanado_public_api.apis.emailtasks_api import EmailtasksApi


class TestEmailtasksApi(unittest.TestCase):
    """ EmailtasksApi unit test stubs """

    def setUp(self):
        self.api = com_yanado_public_api.apis.emailtasks_api.EmailtasksApi()

    def tearDown(self):
        pass

    def test_get_email_tasks(self):
        """
        Test case for get_email_tasks

        Get tasks with emails attached
        """
        pass


if __name__ == '__main__':
    unittest.main()
