# coding: utf-8

"""
    Yanado REST API

    REST API for Yanado

    OpenAPI spec version: 1.0
    Contact: prle@yanado.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import com_yanado_public_api
from com_yanado_public_api.rest import ApiException
from com_yanado_public_api.apis.statuses_api import StatusesApi


class TestStatusesApi(unittest.TestCase):
    """ StatusesApi unit test stubs """

    def setUp(self):
        self.api = com_yanado_public_api.apis.statuses_api.StatusesApi()

    def tearDown(self):
        pass

    def test_get_statuses(self):
        """
        Test case for get_statuses

        Get statuses from a list
        """
        pass


if __name__ == '__main__':
    unittest.main()
