# coding: utf-8

"""
    Yanado REST API

    REST API for Yanado

    OpenAPI spec version: 1.0
    Contact: prle@yanado.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import com_yanado_public_api
from com_yanado_public_api.rest import ApiException
from com_yanado_public_api.apis.comments_api import CommentsApi


class TestCommentsApi(unittest.TestCase):
    """ CommentsApi unit test stubs """

    def setUp(self):
        self.api = com_yanado_public_api.apis.comments_api.CommentsApi()

    def tearDown(self):
        pass

    def test_get_comments(self):
        """
        Test case for get_comments

        Get comments
        """
        pass


if __name__ == '__main__':
    unittest.main()
